Rscript EnsembleModel/rf.svm.xgb.mix.top3.r > log/rf.svm.xgb.mix.top3.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top4.r > log/rf.svm.xgb.mix.top4.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top5.r > log/rf.svm.xgb.mix.top5.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top6.r > log/rf.svm.xgb.mix.top6.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top7.r > log/rf.svm.xgb.mix.top7.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top8.r > log/rf.svm.xgb.mix.top8.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top9.r > log/rf.svm.xgb.mix.top9.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top10.r > log/rf.svm.xgb.mix.top10.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top11.r > log/rf.svm.xgb.mix.top11.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top12.r > log/rf.svm.xgb.mix.top12.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top13.r > log/rf.svm.xgb.mix.top13.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top14.r > log/rf.svm.xgb.mix.top14.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top15.r > log/rf.svm.xgb.mix.top15.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top16.r > log/rf.svm.xgb.mix.top16.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top17.r > log/rf.svm.xgb.mix.top17.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top18.r > log/rf.svm.xgb.mix.top18.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top19.r > log/rf.svm.xgb.mix.top19.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top20.r > log/rf.svm.xgb.mix.top20.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top21.r > log/rf.svm.xgb.mix.top21.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top22.r > log/rf.svm.xgb.mix.top22.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top23.r > log/rf.svm.xgb.mix.top23.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top24.r > log/rf.svm.xgb.mix.top24.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top25.r > log/rf.svm.xgb.mix.top25.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top26.r > log/rf.svm.xgb.mix.top26.r.log
Rscript EnsembleModel/rf.svm.xgb.mix.top27.r > log/rf.svm.xgb.mix.top27.r.log
